### ISSUE TITLE
The download link for 'ResNet-50 Depth Encoder' is broken

### ISSUE THREAD

**Issue by sunqiang85** [YicongHong/Discrete-Continuous-VLN#3]
The download page reports a 404 error

**Comment by YicongHong** [comment]
Thanks for pointing this out, please use the [updated link](https://zenodo.org/api/files/b755f4cc-884e-4774-8320-22c99a526426/gibson-2plus-resnet50.pth?versionId=7f1402ba-af93-46a0-8ec5-4da54ebf1241)

**Comment by gmuraleekrishna** [comment]
Hello Yicong, the new link is also broken

**Comment by YicongHong** [comment]
Hi @gmuraleekrishna, could you please try again? I think it still works. Cheers.

**Comment by jdiazram** [comment]
Hi, 
I try to download "The pre-trained [weights used in our paper (FoV 90 RGB-D)](https://drive.google.com/file/d/1hRdecKWHnKjidIT_i5H5lEGRS53ewWEs/view?usp=drive_link)" but the link is broken (404) and try to download the second link in this issue [update link](https://zenodo.org/api/files/b755f4cc-884e-4774-8320-22c99a526426/gibson-2plus-resnet50.pth?versionId=7f1402ba-af93-46a0-8ec5-4da54ebf1241) but the same result, broken link (404). 
Can you upload it again?
thx
Thx

**Comment by YicongHong** [comment]
Hi @jdiazram, thanks for letting us know. Unfortunately, we are unable to find or access any backup of this checkpoint right now. Could you please use the other two pre-trained weights? Thanks.
