### ISSUE TITLE
Waypoint prediction training code

### ISSUE THREAD

**Issue by gmuraleekrishna** [YicongHong/Discrete-Continuous-VLN#4]
Hello Yicong,

Would you be willing to share the Waypoint_TRM training code?

**Comment by YicongHong** [comment]
Hi There! Yes, we are happy to share the code. Please give us some time to clean it up (and the pre-processed data, which is large so we might just release the sampling code :)
Thanks!

**Comment by TikaToka** [comment]
Any updates for this?

**Comment by yueluhhxx** [comment]
Hi Yicong,

I would like to know if there is any progress about the Waypoint_TRM training code?
Or would you like to share some parameters related to the Waypoint_TRM training, such as the parameters of the Gaussian distribution used to obtain ground-truth heatmap data.

Thanks!

**Comment by wz0919** [comment]
> Hi Yicong,
> 
> I would like to know if there is any progress about the Waypoint_TRM training code? Or would you like to share some parameters related to the Waypoint_TRM training, such as the parameters of the Gaussian distribution used to obtain ground-truth heatmap data.
> 
> Thanks!

We've released the training code and you can try them [here](https://github.com/wz0919/waypoint-predictor.git).
