### ISSUE TITLE
Code errors encountered during eval

### ISSUE THREAD

**Issue by CatLiZi** [YicongHong/Discrete-Continuous-VLN#8]
After training the CMA model, during eval, an error message appeared stating that the file could not be found. I would like to inquire if there are any missing files in the code
FileNotFoundError: [Errno 2] No such file or directory: 'data/connectivity_graphs.pkl'
![1723375489983](https://github.com/user-attachments/assets/dd9e95d1-84ab-4af7-ab95-4b64da40e7d4)

**Comment by madeline-past** [comment]
Hi there,I'd like to ask if you have resolved the problem?I met the same error today.

**Comment by madeline-past** [comment]
I have found 'data/connectivity_graphs.pkl' in https://github.com/jacobkrantz/VLN-CE/

Thanks to https://github.com/MarSaKi/ETPNav/issues/11
