### ISSUE TITLE
Is the adjusted R2R-CE and RxR-CE dataset available?

### ISSUE THREAD

**Issue by lu-renjie** [YicongHong/Discrete-Continuous-VLN#9]
According to the paper, trajectories in R2R-CE dataset is adjusted based on the new connectivity graph, but it seems that it is not available in this repo.

**Comment by YicongHong** [comment]
Hi, we do have the adjusted graphs in this repo. Please see here: https://github.com/YicongHong/Discrete-Continuous-VLN?tab=readme-ov-file#adapted-mp3d-connectivity-graphs-in-continuous-environments

**Comment by lu-renjie** [comment]
Thank you.

**Comment by niyatirawal** [comment]
Where does the code depend on the adapted mp3d connectivity graphs?
